- betamax/cassette/__init__.py
- betamax/matchers/__init__.py
- betamax/serializers/__init__.py
Silences three of the warnings in the pep257 check by changing `__all__` to be immutable tuples, in line with the top level package.
> Make __all__ immutable.

- betamax/configure.py
Should I also include the default value (in parens or otherwise) for these options so they show up [here](https://betamax.readthedocs.org/en/latest/api.html#betamax.configure.Configuration.default_cassette_options)?
> add preserve_exact_body_bytes to docstring

- betamax/matchers/body.py
- tests/unit/test_matchers.py
I was having an issue between python2 and python3 that this appears to have solved. This works for python2 because:
>>> b'' == ''
True
The same is not true for python3 where `recorded_request.body` is a byte-string.
> Use byte string as default in BodyMatcher

- betamax/cassette/interaction.py
- tests/unit/test_cassette.py
This provides a fix to issue #58 by using the `extract_cookies_to_jar` method from `requests` on the `response` object.
> Fix #58: Attach cookies to response object

- betamax/__init__.py
- betamax/adapter.py
Updated docstrings for **pep257** compliance for `__init__.py` and `adapter.py`.  If this looks good, will fix remaining docstrings in order for **travis ci** to pass
```
(betamax)Matts-MacBook-Air:betamax mattchung$ pep257 betamax/__init__.py
(betamax)Matts-MacBook-Air:betamax mattchung$ pep257 betamax/adapter.py
(betamax)Matts-MacBook-Air:betamax mattchung$ 
```
> Fixed flake8 docstring/PEP 257 for init and adapter

- betamax/exceptions.py
- betamax/serializers/proxy.py
Previously, the error message would be along the lines of:
IOError: [Errno 2] No such file or directory: 'vcr/cassettes/test.json'
which isn't too helpful. After this patch, it now raises:
MissingDirectoryError: Configured cassette directory "vcr/cassettes" does not exist - try creating it
> Improve error message if cassettes dir does not exist

- docs/introduction.rst
There was a typo in the first code example.
> Fix typo in code example

- MANIFEST.in
Hello,
without listing patterns it seems that MANIFEST.in is not used correctly.
This is the output of `python setup.py sdist` on `master` branch:
```
running sdist
running egg_info
writing requirements to betamax.egg-info/requires.txt
writing betamax.egg-info/PKG-INFO
writing top-level names to betamax.egg-info/top_level.txt
writing dependency_links to betamax.egg-info/dependency_links.txt
writing entry points to betamax.egg-info/entry_points.txt
writing manifest file 'betamax.egg-info/SOURCES.txt'
reading manifest file 'betamax.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: manifest_maker: MANIFEST.in, line 5: 'recursive-include' expects <dir> <pattern1> <pattern2> ...
warning: manifest_maker: MANIFEST.in, line 6: 'recursive-include' expects <dir> <pattern1> …
```
> Specify patterns for recursive-include directives

- tests/unit/test_serializers.py
> Use os.path.join to be OS independent with regards to paths

- betamax/cassette/cassette.py
- betamax/cassette/interaction.py
- tests/cassettes/test_replays_response_on_right_order.json
- tests/integration/test_record_modes.py
- tests/unit/test_cassette.py
- tests/unit/test_replays.py
Depending on the use case, it may be needed to record the
content of same url different times. Currently only one
url with the same match is allowed. This change proposes two
things:
1. If we are recording, do not query for matches, just record
everything that comes.
2. If we are consuming the cassette, consume each fixture once,
by setting a used flag. This will allow to consume each result
in order, and not duplicate.
Allow to record duplicated urls on a cassette
Depending on the use case, it may be needed to record the
content of same url different times. Currently only one
url with the same match is allowed. This change proposes two
things:
1. If we are recording, do not query for matches, just record
everything that comes.
2. If we are consuming the cassette, consume each fixture …
> Allow to record duplicated urls on a cassette

- betamax/matchers/body.py
- tests/regression/test_requests_2_11_body_matcher.py
Compare bodies appropriately by ensuring both the request body and the recorded body are coerced to bytestrings.
Closes #115 
Closes #114 
cc @bboe. This seems to pass with your regression test on both Requests 2.10.0 and 2.11.0. I'd love your review
> Handle differences in Requests 2.11.0

- .travis.yml
- tests/integration/test_record_modes.py
- tox.ini
httpbin.org added X-Processed-Time header that can possibly differ (and often does), so we need to get rid of it like the Date header.
Other projects noticed this as well, see libwww-perl/Net-HTTP#48
Fixes #146
> Tests: Remove X-Processed-Time header

- docs/source/serializers.rst
- src/betamax/serializers/base.py
- src/betamax/serializers/json_serializer.py
- src/betamax/serializers/proxy.py
- tests/unit/test_serializers.py
- tox.ini
Some serializers return bytes instead of text and we need a way to
indicate that when opening the cassette file.
Related-to gh-123
--- 
cc @wimglenn for review
> Add support for binary serializer storage

- src/betamax/cassette/cassette.py
- tests/unit/test_cassette.py
This enables new_episodes to return the previously recorded interactions
first and then record new ones if necessary.
Closes gh-153
> Fix bug with new_episodes always trying to record

- .travis.yml
Python 3.3 reached EOL a while back and now no longer works with our deps
> Make docstrings required and remove Python 3.3

- src/betamax/cassette/interaction.py
- tests/unit/test_cassette.py
This is to fix #169.
I couldn't think of a better way to test this than to add an additional `.replace` to the `test_replace` test case and if this code doesn't exist, it would alter interaction strings.
> Add shortcircuit condition if text_to_replace is a blank string

- tests/unit/test_fixtures.py
https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly
> tests: fix direct calls to PyTest fixtures

- AUTHORS.rst
- docs/source/configuring.rst
- src/betamax/configure.py
- src/betamax/recorder.py
- tests/integration/test_hooks.py
- tests/unit/test_configure.py
Fixes #178.
This PR adds two new hooks: `cassette_load` and `cassette_eject`. They are called when a cassette is first loaded or when it is ejected, respectively. [Here's a demonstration of the hooks in use along with the corresponding output](https://gist.github.com/jarhill0/72dd9e43d29f2b47d846edc263a0a7f2).
I've also added a little section to the documentation about the new hooks in which I guess that these hooks will be first released with Betamax 0.9.0, which may or may not need to be corrected.
> Add cassette_load and cassette_eject hooks

- docs/source/serializers.rst
- tests/unit/test_serializers.py
There are small typos in:
- docs/source/serializers.rst
- tests/unit/test_serializers.py
Fixes:
- Should read `serialize` rather than `seralize`.
- Should read `behaviour` rather than `beaviour`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- docs/source/serializers.rst
This is a small fix for a broken link in the "Creating Your Own Serializer" section.
> Docs: Fix 'cassette-dict' cross-reference

- tox.ini
The betamax directory was moved into the src directory but the tox workflow was not updated to reflect this change. This commit updates the tox workflow to use the new path.
Refs: #203, cf6aefe
Signed-off-by: Jaremy Hatler <hatler.jaremy@gmail.com>
> fix: update tox workflow to use src/betamax path

- .github/workflows/tox.yml
- .travis.yml
- setup.py
- tox.ini
The list in the classifiers is quite outdated. This updates the list according to the current tested versions.
Note that python 3.7 is already EOL, so this change removes the test with python 3.7 and explicitly requires >=3.8 .
> Update supported python versions

- src/betamax/mock_response.py
- tests/unit/test_cassette.py
https://github.com/betamaxpy/betamax/issues/200
> Implement MockHTTPResponse.close
